POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "author": "Dan Abramov",
  "title": "Overreacted",
  "url": "https://overreacted.io/",
  "userId": "5eb57d6c895abb4c76b4b28b"
}